### PR TITLE
clarify use of docker_add_alias option, addresses #35

### PR DESCRIPTION
**Pull request by slhck**

### CODE REVIEW

**Comment by konstruktoid** [comment]
Thanks @slhck!

**Comment by konstruktoid** [comment]
Can you resubmit as a ... PR?
image

**Comment by slhck** [comment]
Umm. This is a Pull Request by all means. Not sure what is causing this om your end.

**Comment by slhck** [comment]
Interestingly, the Internet has nothing on that specific error. I am unsure what causes it. Maybe you just need to try merging again? (Or try a squash-merge etc.)

**Comment by konstruktoid** [comment]
Really interesting, never seen that before

**Comment by konstruktoid** [comment]
Nope, none of the options worked.

**Comment by konstruktoid** [comment]
I'll try manually

**Comment by konstruktoid** [comment]
Merged manually, and I had to remove the "protected branch" setting for some reason.
Never happend before.

**Comment by konstruktoid** [comment]
Thanks for your contribution :)

**Comment by slhck** [comment]
You're welcome! Thanks for merging this. (Really not sure what the issue was.)

**Pull request merged**
